# -*- mode: ruby -*-
# vi: set ft=ruby

Vagrant.configure("2") do |config|
  config.vm.box = "ubuntu/trusty64"

  config.vm.provider "virtualbox" do |v|
    v.memory = 3172
    v.cpus = 4
  end

  config.vm.network "forwarded_port", guest: 80, host: 8080, protocol: "tcp"
  config.vm.network "forwarded_port", guest: 8888, host: 18888, protocol: "tcp"
  config.vm.network "forwarded_port", guest: 8889, host: 18889, protocol: "tcp"
  config.vm.network "forwarded_port", guest: 5984, host: 15984, protocol: "tcp"
  config.vm.network "forwarded_port", guest: 9200, host: 19200, protocol: "tcp"
  config.vm.network "forwarded_port", guest: 9292, host: 19292, protocol: "tcp"
  config.vm.network "forwarded_port", guest: 443, host: 1443, protocol: "tcp"

  config.vm.network "private_network", ip: "192.168.50.200"
  config.vm.hostname = "cncfloralocal"
  #config.vm.provision :shell, :path => "install_docker_vagrant.sh"
end

